= README

This cli app allows a user to quickly check their nanopool wallets.

== Getting Started

=== Retrieve the Code

You can either clone the codebase or download it directly, I suggest downloading a release.

==== Cloning

. Download and install Git link:https://git-scm.com/downloads[here] if Git is not installed
. Choose a method of cloning using github's documentation link:https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls[here]

.Code Snippet
[source]
----
git clone git@github.com:BZohorskys-Web-Scraping-Repos/Nanopool.git
----

==== Downloading

When downloading you can either download a zip folder of a specific branch of the codebase or download a release provided on github. A link to download the master branch of the codebase can be found link:https://github.com/BZohorskys-Web-Scraping-Repos/Nanopool/archive/refs/heads/master.zip[here]. However, I'd suggest downloading a release as those will be more stable. 

=== Setup a Virtual Environment

. Download and install Python link:https://www.python.org/downloads/[here] if Python is not installed
. Move to the project's top directory
. Create a virtual environment
. Activate the virtual environment
. Install project dependencies

.Code Snippet
[source]
----
cd <to the project's top level directory>
python3 -m venv virtualenv
source virtualenv/bin/activate
pip install -r requirements.txt
----

=== Setup Configuration File

Before you can run the project you will want to configure it to use your wallets. You will need your wallet address and the name of the crypto coin mined on nanopool.

. Open the wallet_addresses.txt file (it should be in the top level project directory. Create it if it does not exist.)
. On one line type your coin's name and then your wallet address, separated by a space.

    Example:
    Bitcoin RBWQX1f9aVEya3VPfmGnkkzwpWx1111111

. Save and close wallet_addresses.txt

== Run Project

. Move to the project's top level directory
. Activate virtual environment
. Execute Code

.Code Snippet (Linux & MacOS)
[source]
----
cd <to the project's top level directory>
source virtualenv/bin/activate
python launcher.py
----

.Code Snippet (Windows)
[source]
----
cd <to the project's top level directory>
.\virtualenv\Scripts\activate.bat
python launcher.py
----

== Project Distribution

This section describes how to create a folder to distribute to others. Note, this folder will contain compiled code which is OS dependent (Windows/Linux/MacOS) meaning only users sharing the same type of of OS can share these distribution folders.

. Move to the project's top directory
. Activate your virtual environment
. Create a folder called "nanopool" located in the dist directory


.Code Snippet (Linux & MacOS)
[source]
----
cd <to the project's top level directory>
source virtualenv/bin/activate
pyinstaller nanopool.spec
----

.Code Snippet (Windows)
[source]
----
cd <to the project's top level directory>
.\virtualenv\Scripts\activate.bat
pyinstaller nanopool.spec
----

== Run Application

. Execute the binary 

.Code Snippet (Linux & MacOS)
[source]
----
./<path-to-distribution-folder>/nanopool
----

.Code Snippet (Windows)
[source]
----
.\<path-to-distribution-folder>\nanopool
----

